### PR TITLE
moar parallel

### PR DESCRIPTION
**Pull request by jfindlay**
Salt is tested in a hyperbolic universe.  I will buy you lunch if you can tell me both puns.

### CODE REVIEW

**Comment by cro** [comment]
Showoff. 😄

**Comment by cachedout** [comment]
A pun between parallels the software and the parallels postulate in hyperbolic geometry (or whatever that is called. I don't remember exactly) and maybe something to do with snapshots in the code and time moving backwards or forwards based on the universe's shape? I'm just guessing on that second one. :]

**Comment by jfindlay** [comment]
Close enough to what I was thinking.  Mike gets a lunch on me.

**Comment by cachedout** [comment]
Since I am a little ways from the office, you may give my free lunch to @thatch45. He probably deserves it more than I do anyhow. :]

**Pull request merged**
